theme: jekyll-theme-slate
title: AWSpot
description: A utility to simplify AWS spot resource management.
logo: https://raw.githubusercontent.com/rob-dalton/rob-dalton.github.io/master/images/awspot/awspot_logo.png
